In [4]:
import math
    

In [5]:
def basic_sigmoid(x):
    s = 1/(1+math.exp(-x))
    return s

In [6]:
basic_sigmoid(-1)

0.2689414213699951

In [7]:
import numpy as np

# result of np.exp
x = np.array([1,2,3])
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692]


In [8]:
# ex of vector operation 
x = np.array([1,2,3])
print(x+3)

[4 5 6]


In [9]:
def sigmoid(x):

    s = 1/(1+np.exp(-x))
    return s

In [10]:
x = sigmoid(np.array([1,2,3]))
x

array([0.73105858, 0.88079708, 0.95257413])

In [11]:
def d_sigmoid(x):

    s = 1/(1+np.exp(-x))
    d = s * (1 - s) 
    return d

In [12]:
x = d_sigmoid(np.array([1,2,3]))
x

array([0.19661193, 0.10499359, 0.04517666])

In [13]:
image = np.random.rand(3,3,2)
image

array([[[0.18334306, 0.56608078],
        [0.81295461, 0.15198555],
        [0.77714302, 0.33003942]],

       [[0.39309309, 0.05615693],
        [0.28845147, 0.39153754],
        [0.80564628, 0.59304436]],

       [[0.40779845, 0.73474762],
        [0.19818712, 0.7758582 ],
        [0.70294819, 0.43426586]]])

In [14]:
def dem_reshape(img):
    img = img.reshape(img.shape[0]*img.shape[1],img.shape[2])
    return img

In [15]:
image = dem_reshape(image)
image

array([[0.18334306, 0.56608078],
       [0.81295461, 0.15198555],
       [0.77714302, 0.33003942],
       [0.39309309, 0.05615693],
       [0.28845147, 0.39153754],
       [0.80564628, 0.59304436],
       [0.40779845, 0.73474762],
       [0.19818712, 0.7758582 ],
       [0.70294819, 0.43426586]])

In [16]:
def normalizerows(img):
    x_norm = np.linalg.norm(img,axis = 1, keepdims = True)
    img = img/x_norm
    return img

image = normalizerows(image)
image

array([[0.30812345, 0.95134638],
       [0.98296917, 0.18377054],
       [0.92043592, 0.39089348],
       [0.98994922, 0.14142326],
       [0.59313256, 0.80510481],
       [0.80533727, 0.5928169 ],
       [0.485284  , 0.87435659],
       [0.2474954 , 0.96888907],
       [0.85074822, 0.52557346]])

In [17]:
img1 = np.array([
    [0,1000,4],
    [2,6,4]])
img1 = normalizerows(img1)
img1

array([[0.        , 0.999992  , 0.00399997],
       [0.26726124, 0.80178373, 0.53452248]])

In [18]:
def softmax(x):
    x_exp = np.exp(x)

    x_sum = np.sum(x_exp, axis = 1 , keepdims = True)

    x = x_exp/x_sum

    return x

img2 = np.array([[9,2,5,0,0],
                 [7,5,0,0,0]])

img2  = softmax(img2)
img2

array([[9.80897665e-01, 8.94462891e-04, 1.79657674e-02, 1.21052389e-04,
        1.21052389e-04],
       [8.78679856e-01, 1.18916387e-01, 8.01252314e-04, 8.01252314e-04,
        8.01252314e-04]])

In [19]:
import time

x1 = np.random.rand(10000000)
x2 = np.random.rand(10000000)

tic = (time.process_time())
dot = 0
for i in range(len(x1)):
    dot += x1[i]*x2[i]
toc = time.process_time()
print("dot  = " +str(dot)+"\n------Computationtime--------" + str(1000*(toc-tic))+"ms")

dot  = 2500576.363881223
------Computationtime--------7046.875ms


In [20]:
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print("dot  = " +str(dot)+"\n------Computationtime--------" + str(1000*(toc-tic))+"ms")

dot  = 2500576.363881265
------Computationtime--------15.625ms


In [45]:
#L1 function

def L1(yhat ,y):
    diff= abs(y-yhat)
    loss=np.sum(diff)
    return loss

yhat=np.array([1,1,1,1,1])
y=np.array([1,1,1,1,1])
print("L1 :"+ str(L1(yhat,y)))

L1 :0


In [55]:
#L2 function

def L2(yhat,y):
    diff=abs(y-yhat)
    loss=np.sum(np.square(diff))
    return loss

yhat=np.array([0.9,0.2,0.1,0.4,0.9])
y=np.array([1,0,0,1,1])
print("L2 :"+str(L2(yhat,y)))

L2 :0.43
